apiVersion: v1
kind: Service
metadata:
  name: {{ include "oas-enhancer.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oas-enhancer.labels" . | nindent 4 }}
    {{- include "oas-enhancer.backend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "oas-enhancer.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
