{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oas-enhancer.fullname" . }}-backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oas-enhancer.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.backend.openaiApiKey | quote }}
{{- end }}
